version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: drf-api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123QWEasd
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://postgres:123QWEasd@db:5432/drf-api-db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  db-data: