# Generated by Django 5.1 on 2024-09-02 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fileload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileload',
            name='user',
        ),
    ]
